export const SURVEY_REQUIREMENTS = [
  {
    title: "How did you heard about us ?",
    subtitle: "Select all that apply",
    options: [
      "Facebook",
      "Instagram",
      "WhatsApp",
      "Email",
      "Call",
      "Google / Website",
      "Referral",
      "Offline",
      "Farmer's Market",
      "Paper Insert",
    ],
    type: "multiple",
    key: "heardFrom"
  },
  {
    title: "Preferred Communication Channel?",
    subtitle: "Select all that apply",
    options: ["Email", "Whatsapp", "Call"],
    type: "multiple",
    key: "preferredCommunication",
  },
  {
    title: "How many people in your household?",
    options: [
      "Just Me",
      "2 Persons",
      "3-4 Persons",
      "5-6 Persons",
      "6 & Above",
    ],
    type: "single",
    key: "household",
  },
  {
    title: "Whats your age group?",
    options: ["20-30", "31-40", "41-50", "51-60", "60 & Above"],
    type: "single",
    key: "age",
  },
  {
    title: "Who makes the purchase decision in your home?",
    options: ["Self", "Parent", "Spouse", "House Help"],
    type: "single",
    key: "purchaseDecision",
  },
  {
    title: "How often do you buy fresh produce?",
    options: ["Weekly", "Twice a week", "Alternate Days", "Daily"],
    type: "single",
    key: "freshPurchase",
  },
  {
    title: "How many meals do you cook at home?",
    options: [
      "2 Meals a day",
      "3 Meals a day",
      "1 Meal a day",
      "4-5 Meals a day",
      "Less then 4 Meals a week",
    ],
    type: "single",
    key: "mealAtHome",
  },
  {
    title: "What's your activity level?",
    options: [
      "Runner",
      "Yoga Practitioner",
      "Gym Enthusiast",
      "Generally Active",
      "Sedentary",
    ],
    type: "single",
    key: "activityLevel",
  },
  {
    title: "What's health benefits are you seeking?",
    subtitle: "Select all that apply",
    options: [
      "Gut Health",
      "Immunity",
      "Weight Loss",
      "Weight Gain",
      "Better Nutrition",
      "Hormonal Balance",
      "Bone Health",
      "Overall Wellness",
    ],
    type: "multiple",
    key: "healthBenefit",
  },
  {
    title: "Any food allergies in your family?",
    subtitle: "Select all that apply",
    options: ["Dairy", "Nuts", "Glutten", "Soya", "Mushrooms", "None"],
    type: "multiple",
    key: "allergy",
    allowCustom: true,
  },
  {
    title: "What cuisines do you prefer?",
    subtitle: "Select all that apply",
    options: ["Indian", "Italian", "Asian", "Mediterranean", "Continental"],
    type: "multiple",
    key: "cuisine",
    allowCustom: true,
  },
  {
    title: "What's your dietary preference?",
    options: [
      "Vegetarian",
      "Non-Vegetarian",
      "Vegan",
      "Eggetarian",
      "Keto",
      "Plant Based",
      "New Food",
    ],
    type: "single",
    key: "diet",
  },
  {
    title: "Any specific health considerations?",
    subtitle: "Select all that apply",
    options: [
      "Diabetes",
      "Blood Pressure",
      "Coronary",
      "Thyroid",
      "Obesity",
      "PCOS/PCOD",
      "Osteoporosis",
      "None",
    ],
    type: "multiple",
    key: "healthConsideration",
  },
  {
    title: "What recipe types interest you?",
    subtitle: "Select all that apply",
    options: [
      "Salads",
      "Soup",
      "Quick 15 min meals",
      "Immunity Boosting",
      "Indian Home-Style",
      "High Protien",
      "Low Calorie",
    ],
    type: "multiple",
    key: "recipe",
    nextTitle: "Submit",
    isSubmit: true,
  },
];
